### ISSUE TITLE
Sending MIDI Start/Stop messages doesn't work

### ISSUE THREAD

**Issue by stevelavietes** [203-Systems/MatrixOS#28]
It looks like the length returned for Start/Stop messages is not set to 1. When I change that (and set MidiPacket::data[0] to the corresponding status), I still get an invalid message with a byte length of 1.

Any ideas?

**Comment by stevelavietes** [comment]
Got this working by also handling the single byte cases within...
  MidiPacket(uint16_t port, EMidiStatus status, ...) {
...prior to the...
status = (EMidiStatus)(status & 0xF0);
...and returning so that it doesn't trigger errant switch cases.

**Comment by 203Null** [comment]
Can you show me a code example on what is causing this issue?

**Comment by stevelavietes** [comment]
A call to...
MatrixOS::MIDI::Send(MidiPacket(0, EMidiStatus::Start));
...(as well as Stop/Continue) does nothing.

This is because...
MidiPacket::Length()
...returns 0 for those statuses (instead of 1).

When that's changed, it sends a byte but the value is wrong.

This is because in...
MidiPacket(uint16_t port, EMidiStatus status, ...) 
...it uses the value of...
status = (EMidiStatus)(status & 0xF0);
...in the switch statement to fill the data members.

A Start status following that & now matches one of the other case conditions and data[0] is filled with 0 (an invalid message).

**Comment by 203Null** [comment]
For some reason I missed this issue. Will fix it soon

**Comment by 203Null** [comment]
Fixed https://github.com/203-Systems/MatrixOS/commit/4815e3212030c380421b411ccf10122afa0eab26 https://github.com/203-Systems/MatrixOS/commit/a23c234c8e7d31cd5720f987eb3d91eee24d9a9c
