### ISSUE TITLE
ErrorHandler default value is invalid

### ISSUE THREAD

**Issue by stevelavietes** [203-Systems/MatrixOS#29]
-    void ErrorHandler(string error = NULL);
+    void ErrorHandler(string error = string());

I got build errors prior to making the above change in MatrixOS.h due to std::string(nullptr) being a deleted interface.

**Comment by 203Null** [comment]
I think this might have to do with the ESP IDF that you are using. I haven’t released a guide on how to compile yet but I believe I’m using 5.0. (I’m away from my development station recently so I’m not entirely sure)

**Comment by 203Null** [comment]
Not sure if this is a 5.1 issue. Close for now until maybe future migration
