### ISSUE TITLE
Matrix Pro keypad jittering

### ISSUE THREAD

**Issue by MichaelMyte** [203-Systems/MatrixOS#36]
Some keypads tend to jitter when applying small forces. Tried increasing debounce time, couldn't get good result.
One thought is to apply longer debounce time or something else if velocity is low(<30), so when gently pushing it won't jitter, and could respond fast if hit hard.
Plus, it might be ideal to set this threshold for individual keys, since not all keys perform the same.

**Comment by 203Null** [comment]
This can be fixed by having a lower note off threshold than the note on threshold. 

I swear I wrote this but it might not get merged.

**Comment by 203Null** [comment]
It seems like this feature was dropped during the last keypad refactoring. I have added it in 7da4ccd

**Comment by 203Null** [comment]
For some reason it got dropped again haha. Added back in with new optimization https://github.com/203-Systems/MatrixOS/commit/def5d3627bd998f7861a1d0213dce5222ee7474f
