### ISSUE TITLE
Note mode enters setting by deafult

### ISSUE THREAD

**Issue by MichaelMyte** [203-Systems/MatrixOS#37]
When entering note mode, I have to press FN to close the setting ui, which doesn't need adjusting every time.
It would be nice to enter note directly without the setting ui, making it smoother.

**Comment by 203Null** [comment]
This is indeed the correct behavior by design at the moment. I will do some survey and see if it need to be changed.

**Comment by 203Null** [comment]
This will be changed in V2.5

**Comment by 203Null** [comment]
Changed in 99fcae391545f5ede6a1f04d5e6402cc1f91b7c1
